# Generated by Django 2.1.7 on 2019-03-23 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barracks',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cadet',
            fields=[
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('xnumber', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('room', models.PositiveSmallIntegerField()),
                ('squad', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('platoon', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('barracks', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ami.Barracks')),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=2, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='GigChoice',
            fields=[
                ('gig', models.CharField(max_length=300, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('room', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('PMI', 'PMI')], max_length=5)),
                ('notes', models.CharField(max_length=200)),
                ('barracks', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ami.Barracks')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ami.Cadet')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('leadershipLevel', models.CharField(choices=[('Team', 'Team'), ('Squad', 'Squad'), ('Platoon', 'Platoon'), ('Company', 'Company'), ('Battalion', 'Battalion'), ('Regiment', 'Regiment'), ('Brigade', 'Brigade')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='gigchoice',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ami.Type'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='gig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ami.GigChoice'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='inspectionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ami.Inspection'),
        ),
        migrations.AddField(
            model_name='cadet',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ami.Company'),
        ),
        migrations.AddField(
            model_name='cadet',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ami.Position'),
        ),
    ]
