# Generated by Django 2.1.7 on 2019-04-03 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ami', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='company',
        ),
        migrations.AddField(
            model_name='room',
            name='barracks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ami.Barracks'),
        ),
    ]
