# Generated by Django 2.1.7 on 2019-03-24 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ami', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadet',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='cadet',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='cadet',
            name='xnumber',
        ),
        migrations.AddField(
            model_name='cadet',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
