# Generated by Django 2.1.7 on 2019-04-03 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ami', '0002_auto_20190403_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='barracks',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ami.Barracks'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
