# Generated by Django 2.1.7 on 2019-03-24 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('ami', '0002_auto_20190324_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('room', models.PositiveSmallIntegerField(null=True)),
                ('squad', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True)),
                ('platoon', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True)),
                ('barracks', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ami.Barracks')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ami.Company')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ami.Position')),
            ],
        ),
        migrations.RemoveField(
            model_name='cadet',
            name='barracks',
        ),
        migrations.RemoveField(
            model_name='cadet',
            name='company',
        ),
        migrations.RemoveField(
            model_name='cadet',
            name='position',
        ),
        migrations.RemoveField(
            model_name='cadet',
            name='username',
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Cadet',
        ),
    ]
