# Generated by Django 2.1.7 on 2019-04-09 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ami', '0003_auto_20190403_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='barracks',
        ),
    ]
