# Generated by Django 2.1.7 on 2019-03-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami', '0003_auto_20190324_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='gigs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inspection',
            name='notes',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
