# Generated by Django 2.1.7 on 2019-03-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ami', '0004_auto_20190324_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gigchoice',
            name='gig',
        ),
        migrations.AddField(
            model_name='gigchoice',
            name='gigDesc',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gigchoice',
            name='gigName',
            field=models.CharField(default=1, max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
