# Generated by Django 2.1.7 on 2019-04-09 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ami', '0004_remove_inspection_barracks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='gigs',
        ),
    ]
