# Generated by Django 2.1.7 on 2019-03-25 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ami', '0006_remove_checklist_gig'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='gig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ami.GigChoice'),
        ),
    ]
