# Generated by Django 2.1.7 on 2019-03-27 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ami', '0007_checklist_gig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='gig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ami.GigChoice'),
        ),
        migrations.AlterField(
            model_name='gigchoice',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ami.Type'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='barracks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ami.Barracks'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='leadershipLevel',
            field=models.CharField(blank=True, choices=[('Team', 'Team'), ('Squad', 'Squad'), ('Platoon', 'Platoon'), ('Company', 'Company'), ('Battalion', 'Battalion'), ('Regiment', 'Regiment'), ('Brigade', 'Brigade')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='barracks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ami.Barracks'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ami.Company'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='platoon',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ami.Position'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='room',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='squad',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True),
        ),
    ]
